name: AOM
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.3
  - pip=20.2.3
  - opencv=4.4.0
  - pip:
    - numpy==1.19.1
    - pandas==1.1.3
    - pillow==7.2.0
    - matplotlib==3.3.2
    - jupyterlab==2.2.8
    - argparse
    - pickle-mixin==1.0.2
    - scipy
